### ISSUE TITLE
segfault when running rpminspect-0.1-0.1.201907302034git.fc30

### ISSUE THREAD

**Issue by tflink** [dcantrell/rpminspect#16]
With the latest rpminspect build, I'm seeing segfaults when I try to run it on multiple systems.

RPMs installed:
* rpminspect-0.1-0.1.201907302034git.fc30
* rpminspect-data-fedora-0.1-0.1.201907151846git.fc30.noarch
* librpminspect-0.1-0.1.201907151823git.fc30.

Environment:
* Fedora 30
* x86_64

Command:
`rpminspect sssd-2.2.0-1.fc30`

Output:
```
$ rpminspect sssd-2.2.0-1.fc30
Segmentation fault (core dumped)
```
[core dump](https://tflink.fedorapeople.org/bugreports/20190731-rpminspect/core.rpminspect.1000.f33cc208efb24feb850b7d9aad20cfd3.13064.1564592876000000.lz4)

**Comment by dcantrell** [comment]
OK, I figured this out and it's not a surprise.  I am almost done with the Java bytecode test and the crash happens there.  The crash happens because your rpminspect.conf file lacks the [javabytecode] block.  That's because I haven't updated rpminspect-data-fedora, so I will do that.  But that's not a good reason for it to segfault.

What I'm doing is adding in a check that will just display an error and keep going with the other tests if you are missing the [javabytecode] block.  You can also skip the javabytecode test by adding "-T \!javabytecode" to the rpminspect command.

I will update rpminspect-data-fedora and also push the fix for rpminspect to keep it from crashing if that block is missing from the config file.
