### ISSUE TITLE
--workdir=~/tmp/rpminspect  creates literal ~ directory in PWD

### ISSUE THREAD

**Issue by hroncok** [dcantrell/rpminspect#22]
$ rpminspect -v --workdir=~/tmp/rpminspect python3-3.7.4-1.fc31 python3-3.7.4-3.fc31

This command creates a directory called literally ~ in PWD. That is somewhat unexpected.

**Comment by dcantrell** [comment]
I agree, that is unexpected.  Though it's not technically wrong.  ~ is a perfectly legal filename character.  :)

I will fix this up.  Thank you for these reports, they are really helpful.

**Comment by dcantrell** [comment]
~ expansion is generally handled by your shell, but when using long options most shells do not expand the ~ character and pass the string directly in the argument vector.

What I have done is add ~ expanding for the workdir argument if you have a ~ in the string.  See the glob(3) man page for details on the functionality.  I am using the GLOB_TILDE_CHECK functionality, so there are some additional checks to ensure the user is there and such.

Since I am relying on glob(3), I will get GLOB_NOMATCH back if the path does not exist.  That is a side effect of using glob(3).  So if you are going to use the long option syntax of rpminspect, keep this in mind.

**Comment by hroncok** [comment]
In other words, if the directory in my home doesn't exists, literal ~ is created, but if it exists, it is used? I bet that this will also bite somebody, but If anything else would be more complicated, i think it is fine.

**Comment by dcantrell** [comment]
It won't create it for workdir because glob() can't successfully expand it.  Before this fix it would create it though because the ~ was carried through to the mkdirp() function.  This fix will prevent that.
